### ISSUE TITLE
Network stringification

### ISSUE THREAD

**Issue by abraxxa** [maxmind/Net-Works#17]
I'd like to start a discussion about how ::Network objects should stringify in case they are in fact addresses (/32 for IPv4 and /128 for IPv6).
We use ::Network objects for attributes that can be networks but also addresses.
Adding another class for that mixed case would be an option as well as changing the stringification of network objects to remove the subnet mask if all bits are set.
What are your opinions?

**Comment by autarch** [comment]
I really don't like the type of "clever" API that would do something different for certain types of networks. Adding a `$network->is_single_address` method would be reasonable. Would that help you?

Also, there's no reason you can't simply wrap Net::Works classes with your own classes which delegate to Net::Works but provide your own custom stringification logic.

**Comment by abraxxa** [comment]
I expected that answer which is why I proposed a third class. Of course if nobody else finds this useful I will add my own subclass which does the stringification the way I need it.
The `$network->is_single_address` method would be helpful of course.
