### ISSUE TITLE
Use of __PACKAGE_ in Net::Works::Address breaks 

### ISSUE THREAD

**Issue by edmundadjei** [maxmind/Net-Works#23]
This issue affects inheritance for
- as_ipv4_string
- previous_ip
- next_ip

below is the test code snippet  that demonstrates the issue

#####################
{
    {
        package Foo;
        use base qw(Net::Works::Address);
    }

    TODO: {

        my $ip = Foo->new_from_string( string => '1.2.3.4' );

        my $next = $ip->next_ip();
        isa_ok(
            $next,
            'Foo',
            'return object of child class for value of ->next_ip'
        );

        my $prev = $ip->previous_ip();
        isa_ok(
            $prev,
            'Foo',
            'return object of child class for value of ->previous_ip'
        );

    }
}
######################

This was noticed during a cv-library pull-request

**Comment by horgh** [comment]
Thanks for reporting this! We merged a fix now.
