### ISSUE TITLE
networks with invalid address/subnet mask combinations are auto-fixed

### ISSUE THREAD

**Issue by abraxxa** [maxmind/Net-Works#7]
I expected this to die:

```
my $net = Net::Works::Network->new_from_string( string => '192.0.2.1/24' );
```

Instead it automagically changes the object to 192.0.2.0/24 which is neither documented nor enables a user to detect such cases.

I'm using it to validate user input, with NetAddr::IP my code looks like this:

```
unless ( $netaddr_obj->addr eq $netaddr_obj->network->addr ) {}
```

which I tried to recreate using Net::Works.

Benchmarks currently show that Net::Works is approximately half as fast as NetAddr::IP which isn't bad without XS.

**Comment by oschwald** [comment]
Rejecting `192.0.2.1/24` would likely break existing code and may slow down the construction of objects further. Given the age of this module, I don't think we are likely to make such a behavior change now. I am going to close this.

**Comment by abraxxa** [comment]
The age of this module or this issue?
I was hoping to replace NetAddr::IP with this module but with such a problematic API we can't do it.

**Comment by oschwald** [comment]
This would be a breaking API change. That seemed more reasonable 5 years ago when this module was still new, but it now would likely cause breakage in code using this module and, as mentioned, the validation would likely slow it down somewhat. If this is important to you, I think we would accept a pull request with an optional strict mode that does this validation.
